server:
  port: 8084
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academicms
    username: academic
    password: "12345678"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
  application:
    name: academicms
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://elaoumrani.com:8444/realms/SchoolManagement
          jwk-set-uri: https://elaoumrani.com:8444/realms/SchoolManagement/protocol/openid-connect/certs

# Configuration pour la sécurité entre services
#service-communication:
  #allowed-ips:
    #- 84.247.189.97:8443  # Plage d'IP internes pour les microservices


# Configuration Feign Client  
feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: full
  circuitbreaker:
    enabled: true